# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0003_auto_20171217_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='likeanswer',
            options={'verbose_name': 'Like for answer', 'verbose_name_plural': 'Like for answers'},
        ),
        migrations.AlterModelOptions(
            name='likequestion',
            options={'verbose_name': 'Like for question', 'verbose_name_plural': 'Like for questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofiles'},
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043b\u0430\u0439\u043a \u0438\u043b\u0438 \u0434\u0438\u0437\u043b\u0430\u0439\u043a'),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043b\u0430\u0439\u043a \u0438\u043b\u0438 \u0434\u0438\u0437\u043b\u0430\u0439\u043a'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.UserProfile', verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
    ]
